### ISSUE TITLE
Rule not triggered for every change

### ISSUE THREAD

**Issue by tomkuijsten** [tfsaggregator/tfsaggregator#123]
I've created multiple rules which worked fine. When a task is moved from our "In progress" to "Review" state I update a column. If I edit the assignee before moving between those states it works fine and the rule gets triggered. However, when I move the task first and immediately change the assignee (using the task board), the rule isn't triggered.

I've disabled the ```rateLimiting``` so I expect each change to trigger the rules immediately.

I'm on TFS 2015 update 2, windows server 2012 update 2 and TFS aggregator 2.1.0 rc2.

**Comment by jessehouwing** [comment]
If the changes happen in too short concession the second update is likely going to hit a "Workitem has changed" exception. Can you capture a debug log using DebugViewer?

**Comment by tomkuijsten** [comment]
I can capture the log, but that won't help. When I enable logging, it seems to work fine. Might be a race condition? Do you think it might help when I enable rateLimiting, or will the same WorkitemHasChanged exception occur?

I'll keep trying to reproduce the error WITH logging today.

**Comment by jessehouwing** [comment]
Rate limiting may kick in, though I'm doubtful. You could up the limit a
bit to see. Though rate limiting must show up in the log, as it raises a
warning.

**Comment by jessehouwing** [comment]
Are you running single apptier or multi?

**Comment by tomkuijsten** [comment]
I run TFS on 1 server, with a separate SQL database server and separate machine for build agents.

**Comment by jessehouwing** [comment]
That runs out two at's picking up in parallel.

I can't seem to repro this on my system unfortunately. If you are able to
capture a log or see anything in the event log, that would help. Or being
able to Co tribute an automated test that shows the behavior.

I suspect that since the kanban column change is team context and not
project context, it may bypass the workitem changed handler. But I'd
consider it a bug on Microsoft's side if that could swallow another field
change at the same time.

**Comment by jessehouwing** [comment]
In the end, remember that we can only trigger post-change and that if changes happen in quick succession they may both come in before we're able to act on the first change. This is inherent to how the TFS ISubscriber works unfortunately.

Unless we drop some marker in a field, say track the revision number we last processed, there's really no way to ensure that the aggregator triggers on every revision, or that the result of the trigger is written to TFS correctly.

I've asked the product team multiple times to provide a real way to "hook" into the save process, so that the boards and open editors refresh after save as well, but so far there's no work being done on that front. Maybe after the new work item form work has completed and moves to on-prem.

**Comment by tomkuijsten** [comment]
Thanks for all the info. It's kind of hard to reproduce. But I do get it from time to time. We have a pretty large trigger collection and I noticed that if one of the triggers fail on an item, the subsequent ones don't get invoked. That could also be a problem (as in, the error might be on my side).

But in the end, as you stated, if you can't trust the system to handle all changes, using it is not an option for us. I understand that it's a Microsoft issue, and not yours.
