### ISSUE TITLE
Support deleting workitem links

### ISSUE THREAD

**Issue by jhughesgit** [tfsaggregator/tfsaggregator#131]
The following exception occurs:
TF237128: Target workitem Id should be set before adding link to collection.

This presumably makes sense as the work item hasn't been saved and had an ID set. Is there a way to save the newly created work item or an alternate solution?

**Comment by jessehouwing** [comment]
Which work items are you trying to link together? Two new work items? Or an
existing and a new workitem?

Can you share your rule?

**Comment by jhughesgit** [comment]
When a Feature with unfinished PBI/Bugs is set to Done I would like to automate the process of duplicating the Feature and moving the unfinished PBI/Bugs to the newly created feature. This has presented a few challenges, most of which I think I can work around.

A snippet of the specific code I am referring to is..

```
var f = store.MakeNewWorkItem((string)self["System.TeamProject"], "Feature");
f["System.Title"] = "(Next Phase) " + self["System.Title"];
// Associate the current feature with the newly created feature
//f.AddWorkItemLink(self, "System.LinkTypes.Related"); // TODO: this link type doesn't work or is incorrect
// Attach the new feature to the Initiative
f.AddWorkItemLink(self.Parent, WorkItemImplementationBase.ParentRelationship); // TF237128: Target workitem Id should be set before adding link to collection.
```
I'm also able to enumerate unfinished PBI/Bugs not sure how to "move" a PBI to the new feature since that would presumably need to involve removing the original parent/child link.

**Comment by giuliov** [comment]
Makes sense. If you look at the samples in https://github.com/tfsaggregator/tfsaggregator/blob/master/IntegrationTests.Plugin/ConfigurationsForTests/NewObjects.policies you will see that they add a Link to an existing work item.

**Comment by jessehouwing** [comment]
Try adding the relationship the other way around.

Self.parent.addworkitemlink(f)

When iterating through the children, you may need to capture them in an
array first to prevent concurrency issues.

**Comment by giuliov** [comment]
To achieve your objective you may try using two rules: the first simply trigger the creation of the new Feature, the second changes the links. You can test that is has been created via a Rule checking the Title and Revision.

**Comment by jhughesgit** [comment]
Thank you for your responses.

**Comment by jhughesgit** [comment]
I hit the stumbling block I suspected might occur from above comment "I'm also able to enumerate unfinished PBI/Bugs not sure how to "move" a PBI to the new feature since that would presumably need to involve removing the original parent/child link."

When I run the following code snippet as a test:

```
var f = store.GetWorkItem(19457);

// Move unfinished children to new feature
foreach (var child in self.Children)
{
	if ((string)child["System.State"] != "Done" && (string)child["System.State"] != "Removed")
	{
		f.AddWorkItemLink(child, WorkItemImplementationBase.ChildRelationship);
	}
}
```
[Critical]    04.223 Exception encountered processing notification: TF201066: You cannot add a Child link to work item 19458 because a work item can have only one Parent link.

I also tried AddWorkItemLink the other way around:
child.AddWorkItemLink(f, WorkItemImplementationBase.ParentRelationship);
and I get this error:
[Critical]    03.719 Exception encountered processing notification: TF201065: Yo
u can not add a Parent link to this work item because a work item can have only
one link of this type.

Is it not possible to move a child work item link to another parent?

**Comment by jessehouwing** [comment]
I don't think we have a delete method for links yet. Just checked...

**Comment by jhughesgit** [comment]
Okay thanks. Delete would presumably require another rule be created (3 rules total) to do what I was looking for so I think I'll stick with the manual process for now. Thanks for your help.

**Comment by mattpdipietro** [comment]
Is there an ETA on when this feature will be available?  In our TFS instance, we're trying to automate the association of bugs found during testing to a parent requirement.  Since we occasionally have multiple requirements tested by a single test case, the method we're taking is:

- if there are multiple requirements, we create a related link to all requirements from the bug WI
- if there is only a single requirement, we create a parent-child relationship between the requirement and bug WI
- as part of our daily triage process, the developer reviews all bugs and removes the automatic associations to unrelated requirements manually
- ideally, once that count gets back to 0, we'd like to change the link type to hierarchy to maintain the parent-child relationship.

It's the last part that we can't currently achieve via aggregator because the existing "related" link type cannot be modified or destroyed, and we end up with two links between the requirement and bug.

Any info on when this might be available would be greatly appreciated so we can either hold off on implementing this process until it is ready, or alter our process to account for the lack of automation.

Thanks--Matt

**Comment by helhaddad** [comment]
Hello,
Is this feature available now? can I remove the parent link between a user story and a taske for example ?
Thanks in advanced for your answer

**Comment by rulep001** [comment]
Hey all,

Found a way to work around this. I used the `DestroyWorkItems` method detailed [here](https://msdn.microsoft.com/en-us/library/microsoft.teamfoundation.workitemtracking.client.workitemstore.destroyworkitems(v=vs.120).aspx). Essentially pass in the work items you want to delete and this should permanently delete them.
