### ISSUE TITLE
Provide property on triggering work item with modified fields that triggered this aggregation

### ISSUE THREAD

**Issue by jessehouwing** [tfsaggregator/tfsaggregator#134]
Use `WorkItemChangedEvent.ChangedFields` this could allow us to postpone the retrieval of work items.

Plus it helps people to decide whether they want to perform an expensive operations. We only have this field available for the workitem that triggered the aggregator.

**Comment by jessehouwing** [comment]
Also configure Rule Policy to optionally check these before triggering a rule to decrease server load.

**Comment by giuliov** [comment]
You propose something along
`<rule name="MyRule" appliesTo="Task,Bug" hasFields="MyCustomField" changedFields="MyCustomField" />`

I would opt instead for exposing an additional property or object, say `changes`. I propose this because
`WorkItemChangedEvent` tell us not just of Fields, but also about links, attachments.
If we try to squeeze all this info in the XML syntax, we will end up with a untangled mess.
We can add some helper so they can write
`if (changes.ContainsField("MyCustomField")) { /*...*/ }`

**Comment by jessehouwing** [comment]
Makes sense.

**Comment by giuliov** [comment]
This add work on implementing #138
