### ISSUE TITLE
Access to the link that was added

### ISSUE THREAD

**Issue by Wylde44** [tfsaggregator/tfsaggregator#144]
Hi, guys!

How can i get access to the link that was added in previous revision?
My task is to understand that the changeset was added, I use "ExternalLinkCount" field but it seems that there are different artifacts can be added with the same linktype.

Thanks!

**Comment by jessehouwing** [comment]
Currently we don't expose the Version Control Links, so there's no way to accurately know when it was added.

**Comment by giuliov** [comment]
@jessehouwing until now we adopted the approach of wrapping the native TFS objects and exposing a limited API to simplify and reduce errors.
I was thinking if we should give up or add an _unsafe_ mode so that users have complete access to underlying model: could be a simple flag in the config file that trigger a different code generation template.
