### ISSUE TITLE
Unable to load DLL 'Microsoft.WITDataStore64.dll'

### ISSUE THREAD

**Issue by helhaddad** [tfsaggregator/tfsaggregator#181]
The description for Event ID 47513 from source TFSAggregator cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Exception encountered processing notification: Unable to load DLL 'Microsoft.WITDataStore64.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E) 
Stack Trace:   at Microsoft.TeamFoundation.WorkItemTracking.Client.DataStore.DataStoreNative64.CreateDatastore(IntPtr& handle)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.DataStore.Datastore..ctor(Object locker)
   at Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemStore.InitializeInternal()
   at Microsoft.TeamFoundation.Client.TfsTeamProjectCollection.InitializeTeamFoundationObject(String fullName, Object instance)
   at Microsoft.TeamFoundation.Client.TfsConnection.CreateServiceInstance(Assembly assembly, String fullName)
   at Microsoft.TeamFoundation.Client.TfsConnection.GetService(Type serviceType)
   at Microsoft.TeamFoundation.Client.TfsConnection.GetService[T]()
   at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.<>c.<ProcessEvent>b__2_0(Uri collectionUri, IdentityDescriptor toImpersonate, IRuntimeContext runtimeContext) in C:\projects\tfsaggregator\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 68
   at Aggregator.Core.Context.RuntimeContext.CreateWorkItemRepository() in C:\projects\tfsaggregator\Aggregator.Core\Context\RuntimeContext.cs:line 170
   at Aggregator.Core.Context.RuntimeContext.get_WorkItemRepository() in C:\projects\tfsaggregator\Aggregator.Core\Context\RuntimeContext.cs:line 183
   at Aggregator.Core.EventProcessor..ctor(IRuntimeContext runtime) in C:\projects\tfsaggregator\Aggregator.Core\EventProcessor.cs:line 40
   at TFSAggregator.TfsSpecific.WorkItemChangedEventHandler.ProcessEvent(IVssRequestContext requestContext, NotificationType notificationType, Object notificationEventArgs, Int32& statusCode, String& statusMessage, ExceptionPropertyCollection& properties) in C:\projects\tfsaggregator\Aggregator.ServerPlugin\WorkItemChangedEventHandler.cs:line 84

the message resource is present but the message is not found in the string/message table

**Comment by giuliov** [comment]
You have an installation problem because a DLL is missing (`Unable to load DLL 'Microsoft.WITDataStore64.dll'`).

Can you please add more information (see [Install](https://github.com/tfsaggregator/tfsaggregator/wiki/Install) in the wiki)? How you tried to install? What's in the install log (see #139)?

**Comment by helhaddad** [comment]
I installed on my TFS server 2015 Update 3, its works
and i installed it in another TFS server same version 2015 Update 3 it not working, it shows me this error in the event viewer.

I followed the installation steps in the letter

**Comment by helhaddad** [comment]
the rule contains no errors, I tested it by the app.exe

**Comment by giuliov** [comment]
As I wrote, it is a setup problem, not a rule issue: for some reason the file `Microsoft.WITDataStore64.dll` is missing.
You can search for it and copy the file from the other system, the one working.
I can guess that there are differences between the two servers, maybe on one is installed Visual Studio and not on the other. The server have the same operating system?

As explained in #139, it would be interesting to have a detailed log to examine:
```
msiexec /x TFSAggregator-2.1.203-Release.msi /L*v uninstall.log
msiexec /i TFSAggregator-2.1.203-Release.msi /L*v install.log
```
The log are very verbose, avoid pasting their content here, use a Gist instead and refer them in the reply through a link. More important **sanitize** the content of these files before uploading (e.g. machine name, accounts).

**Comment by helhaddad** [comment]
thank you very much for your response, I'll send you the logs ASAP

**Comment by helhaddad** [comment]
thank you very much for your response, I'll send you the logs ASAP

**Comment by helhaddad** [comment]
Hello,

Attached the instalation logs

[Logs.zip](https://github.com/tfsaggregator/tfsaggregator/files/486985/Logs.zip)

**Comment by helhaddad** [comment]
My tfs its an Upgrade from 2013 version to 2015.3
for the Aggregator uninstalled between upgrades.
i installed Aggregator for 2015.2.

The Microsoft.WITDataStore64.dll its present in the folder C:\Program Files\Microsoft Team Foundation Server 14.0\Application Tier\Web Services\bin\

**Comment by giuliov** [comment]
It is fine: Update 3 is compatible with Update 2. The missing file should be in three locations
![2016-09-22_230451](https://cloud.githubusercontent.com/assets/1869724/18766147/1248b32e-8119-11e6-921a-df7f48b1fc7d.png)

In your logs, lines 2275-2278 confirms that TFSAggregator was installed. One thing that caught my eyes is the `MsiSystemRebootPending = 1`; this usually means that the machine was patched and is waiting a reboot to complete setup.

The error happens when Aggregator is connecting back to TFS. For the client application I had to manually add it to the setup, but it is not needed by the server plugin.
So I am thinking that it could be something different. Please review the [Troubleshooting](https://github.com/tfsaggregator/tfsaggregator/wiki/Troubleshooting) page and in particular these:

- the user connecting to TFS (LocalService and NetworkService have no permissions) and/or the [`autoImpersonate`](https://github.com/tfsaggregator/tfsaggregator/wiki/Policy-Syntax) option
- the URL, you can force it through the [`server/@baseUrl` configuration option](https://github.com/tfsaggregator/tfsaggregator/wiki/Policy-Syntax)
-

**Comment by helhaddad** [comment]
I add Microsoft.WITDataStore64.ddl to sytstem32 folder and Aggregator work fine !!!

**Comment by jessehouwing** [comment]
That is a *very scary* solution...

**Comment by giuliov** [comment]
At least this proof that we need to consider that DLL, but I do not see why it is needed in @helhaddad environment.

**Comment by jessehouwing** [comment]
It should be pre-loaded by TFS automatically. I can't see why it wouldn't
be finding it. I'd love to see a Process Explorer shows as loaded modules:

https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx
https://kb.froglogic.com/display/KB/Getting+a+list+of+DLLs+currently+loaded+in+a+process

And I'd love to see the output from: `dir /s "c:\Program Files\Microsoft
Team Foundation Server 14.0"` and the contents of the system environment's
PATH variable for the TFS service user.

`runas /profile /user:domain\tfs_service "cmd /c echo %path%"`
