### ISSUE TITLE
Creating Child Tasks.

### ISSUE THREAD

**Issue by tlf123** [tfsaggregator/tfsaggregator#196]
This is just a question, and maybe an enhancement if it can't already be done.

When creating Child Tasks (which works well) can you only have it happen on initial creation?

We have instances when the Tasks may not be required so we would remove them, but they get created right back. Moving them to Done works, but does not fit our end goal of tracking Tasks that have work associated with them.

If we can have it just so that it creates the Tasks when the Parent is initially created and if removed they stay removed this would fit our needs.

**Comment by jessehouwing** [comment]
Due to how sparsification works (automatic setting of backlog priority) the
event of 'new' gets lost...

But you could check whether the revision is above a certain number and
otherwise crawl the previous iterations.

Alternatively you could create a 'hidden' field where you u store whether
the rule has triggered in the past.

**Comment by giuliov** [comment]
You can also try using the `Revision` property, e.g.
```
if (self.Revision < 2) { /*...create children...*/ }
```
it is not 100% bullet proof, maybe you need to test for 3 or 4, but at least can limit the number of unwanted creations.
