### ISSUE TITLE
Cycles and infinite loop check

### ISSUE THREAD

**Issue by giuliov** [tfsaggregator/tfsaggregator#20]
We could drop a context Guid in the comments of a save action and check the history to see if the last save was done using the same Guid. Or a custom field if people want to keep the history clean.

See <https://social.msdn.microsoft.com/Forums/vstudio/en-US/36e4bfbb-fd93-4ea8-b0f9-945d2cdc682d/workitemchangedevent-is-work-item-already-written-to-database?forum=tfsworkitemtracking> for some scenario.

**Comment by rbanks54** [comment]
We will want to avoid anything that requires customisation of the work item fields in order to use the aggregator. I think a check of the WI history to see if the aggregator made the changes and/or caching recently saved work items (e.g. last 30 secs) in memory and checking against them before doing any processing could work.

**Comment by jessehouwing** [comment]
+1 for work item history. Keeping in memory would not work in a multi-AT setup, unless some kind of distributed cache is employed. I'd like to stay away from such a solution for now.

**Comment by jessehouwing** [comment]
Can we simply check for number of revisions/minute by the same user and stop when it passes a certain configurable threshold to begin with? We already have the work item and thus the revisions and their timestamp at hand. 

In case we skip an update due to the threshold being passed, we probably do need to raise a warning in the eventlog.

**Comment by giuliov** [comment]
Seems reasonable, like the 32 recursive calls in SQL Server.
Pros: all information is available, cons: it may slow down (peeking at History may trigger additional DB queries).
Enabled by default can be disabled in the runtime section of configuration file.

**Comment by jessehouwing** [comment]
@rbanks54, @giuliov feedback welcome. need to deploy it to a test TFS server to see how this behaves.

**Comment by jessehouwing** [comment]
For single tier servers keeping track of the last X saved work item ID's in memory would be a faster solution. A simple queue would allow us to keep track of up to X saved work items and just loop through it before saving.

**Comment by jessehouwing** [comment]
First implementation tested and checked in. It tries to reduce the number of roundtrips by being clever.
