### ISSUE TITLE
Add errors to WorkItem history

### ISSUE THREAD

**Issue by giuliov** [tfsaggregator/tfsaggregator#22]
Add errors to ... TFS alerts? WorkItem history?

**Comment by rbanks54** [comment]
Since it's a server side plug in, errors should go to the event log. It'll be the easiest place to see problems and for any IT Pros who might be administering the system it's the one place they're going to be looking.

P.S. Putting errors in WorkItems or Alerts would require a connection to TFS, which means errors related to connectivity could never be reported.

**Comment by giuliov** [comment]
It is a Jesse idea, in addition to usual destination, to enable also this type of logging. I think the scenario is for non-administrators that create the calculation rules. If the rule source are under version control, one do not even need admin rights to re-deploy.

**Comment by jessehouwing** [comment]
That's thee idea. To allow decentralized editing, decentralized logging is required... Some of the TFS instances I work with are "owned" by 100's of people. Each doing template customizations and other crazy things. You own everything up to the collection level. This is catering towards that.

**Comment by jessehouwing** [comment]
Won't fix
