### ISSUE TITLE
Need help with the time tracking calculation.

### ISSUE THREAD

**Issue by SAnCherepan** [tfsaggregator/tfsaggregator#224]
Hello!

We are having trouble with our time tracking rules.

### The rules
For our time tracking we use this set of rules:
- Rule 1:
```C#
<rule name="Check_Completed_Work" appliesTo="*" hasFields="Microsoft.VSTS.Scheduling.CompletedWork">
    <![CDATA[
        if (self.HasChildren())
        {
            double checkedValue = self.Children
                .Where(child => child.Fields.Any(field => field.ReferenceName == "Microsoft.VSTS.Scheduling.CompletedWork"))
                .Sum(child => (double)(child["Microsoft.VSTS.Scheduling.CompletedWork"]??0d));
		
            if((checkedValue != (double)(self["Microsoft.VSTS.Scheduling.CompletedWork"]??0d)))
            {
	        self["Microsoft.VSTS.Scheduling.CompletedWork"] = checkedValue;
	    }
        }
    ]]>
</rule>
```
- Rule 2:
```C#
<rule name="Completed_Work_Calc" appliesTo="*" hasFields="Microsoft.VSTS.Scheduling.CompletedWork;Custom.Previous.Completed.Work">
    <![CDATA[
        if((double)(self["Microsoft.VSTS.Scheduling.CompletedWork"]??0d) < 0)
        {
            self["Microsoft.VSTS.Scheduling.CompletedWork"] = 0;
        }

        if (self.HasParent() && self.Parent.Fields.Any(field => field.ReferenceName == "Microsoft.VSTS.Scheduling.CompletedWork"))
        { 
            double delta =(double)(self["Microsoft.VSTS.Scheduling.CompletedWork"]??0d) - (double)(self["Custom.Previous.Completed.Work"]??0d);
            if(delta != 0)
            {
                self.Parent["Microsoft.VSTS.Scheduling.CompletedWork"] = (double)(self.Parent["Microsoft.VSTS.Scheduling.CompletedWork"]??0d) + delta;

                self["Custom.Previous.Completed.Work"] = (double)(self["Microsoft.VSTS.Scheduling.CompletedWork"]??0d);
            }
        }	
    ]]>
</rule>  			
```
Rule 1 rolls through all the children and sums up the value.
Rule 2 reflects iterational changes from a single child. This one does most of the job, but it cannot help when the task gets added to a new parent or removed at all. That is why we need the Rule 1.

### The problem
This set has but a single flaw (one that we can see anyway): whenever you remove **the last** child item (or move it to another parent), the old (previous) parent keeps Completed Work (CW) of the leaving child, the value does not get zeroed.
Obviously, the reason is the guard condition on the Rule 1: `if (self.HasChildren())`, so when the last child leaves, it keeps the logic from updating CW. Yet, removing this condition would cause any WI with no children to always set its CW to zero, which is clearly undesirable.
We could not find a way to extend the guard condition, without firing the rule on any other, unintended occasions, like removing a non-child link, or to handle this case any other way.
Naturally, we studied the wiki, both old and new, but still were unable to find a solution.

### Software versions
TFS version: 2015 Update 3 (planning to upgrade to the latest stable 2017 shortly-ish)
TFSAggregator version: 2.1.1 (planning to upgrade to the latest stable version along with the TFS upgrade)

Would you have any suggestions?
Thank you for your time and effort.

**Comment by giuliov** [comment]
At first glance, you should track if the parent had children in the past. You can use a rule that set an hidden custom field or add a tag when you first notice a children has been added.

Giulio
(typed on a mobile screen... Be patient and forgiving)

----- Messaggio originale -----
Da: "SAnCherepan" <notifications@github.com>
Inviato: ‎06/‎04/‎2017 14:46
A: "tfsaggregator/tfsaggregator" <tfsaggregator@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Oggetto: [tfsaggregator/tfsaggregator] Need help with the time trackingcalculation. (#224)

Hello!
We are having trouble with our time tracking rules.
The rules
For our time tracking we use this set of rules:
Rule 1: 
<rule name="Check_Completed_Work" appliesTo="*" hasFields="Microsoft.VSTS.Scheduling.CompletedWork">
    <![CDATA[
        if (self.HasChildren())
        {
            double checkedValue = self.Children
                .Where(child => child.Fields.Any(field => field.ReferenceName == "Microsoft.VSTS.Scheduling.CompletedWork"))
                .Sum(child => (double)(child["Microsoft.VSTS.Scheduling.CompletedWork"]??0d));
		
            if((checkedValue != (double)(self["Microsoft.VSTS.Scheduling.CompletedWork"]??0d)))
            {
	        self["Microsoft.VSTS.Scheduling.CompletedWork"] = checkedValue;
	    }
        }
    ]]>
</rule>Rule 2: 
<rule name="Completed_Work_Calc" appliesTo="*" hasFields="Microsoft.VSTS.Scheduling.CompletedWork;Custom.Previous.Completed.Work">
    <![CDATA[
        if((double)(self["Microsoft.VSTS.Scheduling.CompletedWork"]??0d) < 0)
        {
            self["Microsoft.VSTS.Scheduling.CompletedWork"] = 0;
        }

        if (self.HasParent() && self.Parent.Fields.Any(field => field.ReferenceName == "Microsoft.VSTS.Scheduling.CompletedWork"))
        { 
            double delta =(double)(self["Microsoft.VSTS.Scheduling.CompletedWork"]??0d) - (double)(self["Custom.Previous.Completed.Work"]??0d);
            if(delta != 0)
            {
                self.Parent["Microsoft.VSTS.Scheduling.CompletedWork"] = (double)(self.Parent["Microsoft.VSTS.Scheduling.CompletedWork"]??0d) + delta;

                self["Custom.Previous.Completed.Work"] = (double)(self["Microsoft.VSTS.Scheduling.CompletedWork"]??0d);
            }
        }	
    ]]>
</rule>  			Rule 1 rolls through all the children and sums up the value.
Rule 2 reflects iterational changes from a single child. This one does most of the job, but it cannot help when the task gets added to a new parent or removed at all. That is why we need the Rule 1.
The problem
This set has but a single flaw (one that we can see anyway): whenever you remove the last child item (or move it to another parent), the old (previous) parent keeps Completed Work (CW) of the leaving child, the value does not get zeroed.
Obviously, the reason is the guard condition on the Rule 1: if (self.HasChildren()), so when the last child leaves, it keeps the logic from updating CW. Yet, removing this condition would cause any WI with no children to always set its CW to zero, which is clearly undesirable.
We could not find a way to extend the guard condition, without firing the rule on any other, unintended occasions, like removing a non-child link, or to handle this case any other way.
Naturally, we studied the wiki, both old and new, but still were unable to find a solution.
Software versions
TFS version: 2015 Update 3 (planning to upgrade to the latest stable 2017 shortly-ish)
TFSAggregator version: 2.1.1 (planning to upgrade to the latest stable version along with the TFS upgrade)
Would you have any suggestions?
Thank you for your time and effort.

**Comment by SAnCherepan** [comment]
The custom boolean field set to true if the HasChildren() is true. The suggestion seems solid, will give it a go and reply with results when I'm back at work.

Many thanks!

**Comment by SAnCherepan** [comment]
Guilio,
Proposed solution works with all the new cases, but items with their child links already removed will not be affected.
It is a good enough workaround, the reason I didn't find it was that I was looking for something like `Revision.Links`, which is present in [Microsoft.TeamFoundation.WorkItemTracking.Client](https://msdn.microsoft.com/en-us/library/microsoft.teamfoundation.workitemtracking.client.revision(v=vs.120).aspx). 
It is currently not exposed in your [RevisionWrapper](https://github.com/tfsaggregator/tfsaggregator/blob/master/Aggregator.Core/Facade/RevisionWrapper.cs), so I would like to propose exposing those links as a new feature for one of the future releases.
