### ISSUE TITLE
Is it necessary to set make-requests-on-behalf-of-others-permission to true in order to properly use authentication autoImpersonate="true"?

### ISSUE THREAD

**Issue by tfs-dev** [tfsaggregator/tfsaggregator#236]
In order to properly use autoImpersonate set to true in TFSAggregator2.ServerPlugin.Policies, i.e.:

        
        <authentication autoImpersonate="true" />

is it necessary to set the following permission to true for "Project Collection Valid Users" group?
https://www.visualstudio.com/en-us/docs/setup-admin/permissions#make-requests-on-behalf-of-others-permission

**Comment by jessehouwing** [comment]
Yes

On Jul 7, 2017 16:25, "tfs-dev" <notifications@github.com> wrote:

In order to properly use autoImpersonate set to true in
TFSAggregator2.ServerPlugin.Policies, i.e.:

    
    <authentication autoImpersonate="true" />

is it necessary to set the following permission to true for "Project
Collection Valid Users" group?
https://www.visualstudio.com/en-us/docs/setup-admin/
permissions#make-requests-on-behalf-of-others-permission

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tfsaggregator/tfsaggregator/issues/236>, or mute the
thread
