### ISSUE TITLE
Question:  Determining the team's current sprint start/end dates from a rule?

### ISSUE THREAD

**Issue by RangerDjanger** [tfsaggregator/tfsaggregator#242]
Hi there,

I'd like to know peoples thoughts on how I could go about creating a rule that adds a 'tag' to a work item, if that work item is added in the current sprint. E.g. "unplanned work" tag.

Initial thoughts is if i can determine if the work item is added on day one of the current sprint, that will suffice.

Any ideas on APIs to call from a rule to make this happen?

Thanks.

**Comment by jessehouwing** [comment]
Currently we don't expose that information.

There is a rest API I know of that exposes this information, not sure if
it's available from the old classification node api.

This sounds useful. If you want to submit a pull request with a utility
function, similar to Send mail that would work for us. Otherwise we'll
triage this for a future release.
