### ISSUE TITLE
Related Link

### ISSUE THREAD

**Issue by VermaKrishna** [tfsaggregator/tfsaggregator#250]
Hi All,
We have created a policy .
logic:

Workitem name: BUG
Linked multiple bugs using "Child"  Link type .
now this policy updated a filed "Custom.ChildLink" with Id's of all linked Bugs.

Here is the code:
if (self.related())
			{
				foreach (var child in self.Children)
				{
				link+= child["System.Id"]+",";
				}
				link=link.Substring(0,link.Length-1);
				self["Custom.ChildLink"]=link;

How can i extend it to Link Type "Related".
Help greatly appreciated.

Thanks
Krishna

**Comment by jessehouwing** [comment]
Use the links property or followlinks function to grab all related links.
Be careful though, related links don't trigger changes on both ends and
related links are very easy to cause a cascade.

Be sure to sort the list if ids before saving to prevent accidentally
causing a loop should the order be nonsequential at times.

On Oct 5, 2017 08:20, "VermaKrishna" <notifications@github.com> wrote:

Hi All,
We have created a policy .
logic:

Workitem name: BUG
Linked multiple bugs using "Child" Link type .
now this policy updated a filed "Custom.ChildLink" with Id's of all linked
Bugs.

Here is the code:
if (self.related())
{
foreach (var child in self.Children)
{
link+= child["System.Id"]+",";
}
link=link.Substring(0,link.Length-1);
self["Custom.ChildLink"]=link;

How can i extend it to Link Type "Related".
Help greatly appreciated.

Thanks
Krishna

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tfsaggregator/tfsaggregator/issues/250>, or mute the
thread

**Comment by VermaKrishna** [comment]
Can you please provide me example.

Thanks

**Comment by jessehouwing** [comment]
I'd prefer not to. We're already spending quite a bit of time to make sure the tool working and to help people fix strange problems. This is not very hard to figure out if you know a bit of code, we have unit tests around the link traversal code and even an example on following links through the docs wiki.

https://tfsaggregator.github.io/using/examples/accumulate-to-grand-parent/
https://github.com/tfsaggregator/tfsaggregator/blob/master/UnitTests.Core/NavigationTests.cs#L132

**Comment by VermaKrishna** [comment]
Thanks.
Was able to expand it to Related Now.

**Comment by VermaKrishna** [comment]
Thanks
