### ISSUE TITLE
AddWorkItemLink between new Items

### ISSUE THREAD

**Issue by dr-zone** [tfsaggregator/tfsaggregator#251]
I have following rule; when a bug has been created I want to automaticly add 2 new workitems.
The issue is I want to link the two newly created Tasks.

```
<rule name="AutoCreateTaskOnBug" appliesTo="Bug" hasFields="System.Title,System.IterationId,System.AreaPath">
<![CDATA[
    var parent = self;
    if (!self.HasChildren())
    {
        // use self to pass in the Team Project Context
        var devTask = store.MakeNewWorkItem((string)self["System.TeamProject"], "Task");
        devTask["Title"] = "Resolve Bug";
        devTask.AddWorkItemLink(parent, WorkItemImplementationBase.ParentRelationship);
		
	var testTask = store.MakeNewWorkItem((string)self["System.TeamProject"], "Task");
        testTask["Title"] = "Test Bug";
	testTask.AddWorkItemLink(parent, WorkItemImplementationBase.ParentRelationship);
	
	testTask.AddWorkItemLink(devTask, "Predecessor");
    }
    ]]>
</rule>
```

The error I get while executing the rule is:
```
[Information] 01.469 Adding work item link 'Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemLinkTypeEnd' from #0 to #0
[Critical]    01.480 Exception encountered processing notification: TF237128: Target workitem ID should be set before adding link to collection.
```

How can I create a link between the newly created items?

**Comment by jessehouwing** [comment]
Only from the newly created child to the parent, not the other way around.

And in your case what's failing is from the dev tast to the test task. When
both ends are new the save will fail. You'd have to have a second rule that
triggers on the creation of a new task/testcase and links the two together
through the parent.

This is a limitation of the object model.

On Oct 6, 2017 13:55, "dr-zone" <notifications@github.com> wrote:

I have following rule; when a bug has been created I want to automaticly
add 2 new workitems.
The issue is I want to link the two newly created Tasks.

<rule name="AutoCreateTaskOnBug" appliesTo="Bug"
hasFields="System.Title,System.IterationId,System.AreaPath">
<![CDATA[
    var parent = self;
    if (!self.HasChildren())
    {
        // use self to pass in the Team Project Context
        var devTask =
store.MakeNewWorkItem((string)self["System.TeamProject"], "Task");
        devTask["Title"] = "Resolve Bug";
        devTask.AddWorkItemLink(parent,
WorkItemImplementationBase.ParentRelationship);
		
	var testTask =
store.MakeNewWorkItem((string)self["System.TeamProject"], "Task");
        testTask["Title"] = "Test Bug";
	testTask.AddWorkItemLink(parent,
WorkItemImplementationBase.ParentRelationship);
	
	testTask.AddWorkItemLink(devTask, "Predecessor");
    }
    ]]>
</rule>

The error I get while executing the rule is:

[Information] 01.469 Adding work item link
'Microsoft.TeamFoundation.WorkItemTracking.Client.WorkItemLinkTypeEnd'
from #0 to #0
[Critical]    01.480 Exception encountered processing notification:
TF237128: Target workitem ID should be set before adding link to
collection.

How can I create a link between the newly created items?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tfsaggregator/tfsaggregator/issues/251>, or mute the
thread
