### ISSUE TITLE
Expose info who launched the rule

### ISSUE THREAD

**Issue by gino983** [tfsaggregator/tfsaggregator#263]
You can read the **name** of the user who launches the rule to save username in to personal field?

this is very useful to save those who launched the rule.

**Comment by giuliov** [comment]
No, but could be a nice feature to add

**Comment by gino983** [comment]
I tried and with the **Changed By**  I already have who is changing the rule. If you **Impersonate = false** you will always see the **administrator** user and not the user who launched the rule.

**Comment by jessehouwing** [comment]
The user triggering the change is the user of the PreviousRevision in that
case, unless rules are cascading the triggering of new rules.

On Nov 8, 2017 14:15, "Gino" <notifications@github.com> wrote:

I tried and with the *Changed By* I already have who is changing the rule.
If you *Impersonate = false* you will always see the *administrator* user
and not the user who launched the rule.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tfsaggregator/tfsaggregator/issues/263#issuecomment-342814098>,
or mute the thread
