### ISSUE TITLE
Prevent event trigger from within rule causing the event

### ISSUE THREAD

**Issue by jdshkolnik** [tfsaggregator/tfsaggregator#276]
Hi,

Below code is based on scrum template where epic can have one or more feature children. If a feature is updated, it will aggregate effort for all of its parent epic's children which, in turn, will trigger the epic's rule to aggregate effort of all its children. Is there any way to bypass/suppress the second trigger? The parent's rule is necessary as a workaround to being unable to respond to deleted children (#275) but I imagine it'd be handy in other cases as well.

```
  <rule name="RollupEpics" changes="New,Change,Restore" appliesTo="Epic"><![CDATA[
    if (self.HasChildren())
    {
        self["Microsoft.VSTS.Scheduling.Effort"] = self.Children.Where(req => req["System.State"].ToString() != "Removed").Sum(req => req.GetField<double>("Microsoft.VSTS.Scheduling.Effort", 0d));
    }
    ]]></rule>
  
  <rule name="RollupFeatures" changes="New,Change,Restore" appliesTo="Feature"><![CDATA[
    if (self.HasParent())
    {
        var parent = self.Parent;
        
        if (parent.TypeName == "Epic")
        {
            parent["Microsoft.VSTS.Scheduling.Effort"] = parent.Children.Where(req => req["System.State"].ToString() != "Removed").Sum(req => req.GetField<double>("Microsoft.VSTS.Scheduling.Effort", 0d));
        }
    }
    
    if (self.HasChildren())
    {
        self["Microsoft.VSTS.Scheduling.Effort"] = self.Children.Where(req => req["System.State"].ToString() != "Removed").Sum(req => req.GetField<double>("Microsoft.VSTS.Scheduling.Effort", 0d));
    }
    ]]></rule>
```

**Comment by jessehouwing** [comment]
Only when introducing a custom field where you add so your rule can use it
to make a judgment call. (possibly the history field, though this may cause
pollution of the discussion field.)

Or possibly using a time based mechanism to prevent updates based on a
certain field within x secs.

Or by checking the user who made the last change (in case you're not using
impersonation).

There is no built in mechanism in the plugin itself, since we lack the
information to base such a decision on...

**Comment by jessehouwing** [comment]
Worst case you will recalculate the value, try to store it, we will detect that no real changes occurred and we'll skip the save.
