### ISSUE TITLE
calculate the total days between two DateTime objects

### ISSUE THREAD

**Issue by ShabiLev** [tfsaggregator/tfsaggregator#282]
Hi, I’m new to this environment and will appreciate the help

I have trouble to calculate the total days between two DateTime objects.

<![CDATA[
If (self["TS.First"] != null && self["TS.Second"] != null)
	{
self["TS.TotalDays"] = ((double)(DateTime)self["TS.Second "] - (double)(DateTime)self["TS. First "]).TotalDays;
	}
]]>

Thanks

**Comment by jessehouwing** [comment]
(Datetime - Datetime).TotalDays from the top of my head.

**Comment by ShabiLev** [comment]
thanks jessehouwing
that was what i tried, see below

<![CDATA[
If (self["TS.First"] != null && self["TS.Second"] != null)
	{
self["TS.TotalDays"] = ((double)(DateTime)self["TS.Second "] - (double)(DateTime)self["TS. First "]).TotalDays;
	}
]]>

**Comment by jessehouwing** [comment]
Don't casts to double, just subtract the two dates to get an instance of TimeSpan.

**Comment by ShabiLev** [comment]
Thank you again,
Tried that in couple of variations but without success.
See again below.
Could that be because of the date formats?
[new  3.txt](https://github.com/tfsaggregator/tfsaggregator/files/1855118/new.3.txt)

**Comment by jessehouwing** [comment]
What's the error you're getting? Are both fields of type Datetime? Add some log statements to have an idea of what you're dealing with.

I suggest logging the datatype of the fields, their values prior to doing any calculations with them etc.

**Comment by IronGem** [comment]
I just finished writing a rule to do just this.  Instead of using the .TotalDays property, which returns a TimeSpan object, I used the .Days property which returns an int.  
`self["intDaysField"] = ((System.DateTime)self["DateFieldName"] - System.DateTime.Today).Days;`
if your date is after today and you are counting down, or
`self["intDaysField"] = (System.DateTime.Today - (System.DateTime)self["DateFieldName"]).Days;`
if your date is before today and you are counting up.  Of course I checked for null in the surrounding `if` statement. If you don't you could use the `self.GetField<System.DateTime>("DateFieldName", [defaultValueIfNull])` method
Hope this helps
