### ISSUE TITLE
Automatic generation of a tree of work items. 

### ISSUE THREAD

**Issue by IronGem** [tfsaggregator/tfsaggregator#287]
Thank you for the excellent plugin.  Our organization relies on this extensively.  

My current situation is most of our new projects follow a pattern so we need a standard tree/set of Work items when a new project is approved.  I have been looking into the MakeNewWorkItem method which looks like it will work for the most part.  The only issue I have, is how to be able to link all of the new work items in a tree when the tree will be 2-3 levels deep (parent-child relationships)?  The AddWorkItemLink method only works if at least one of the items is already saved in TFS.  Is there a .Save() method in the IWorkItemExposed class that could be used to facilitate this?
Also, Is there any way to create custom classes or enums while using C# code?  This ability would make dynamically generating work items based on a template much easier.

If this functionality is outside the scope of this tool, please let me know.  If anyone knows of a tool that already does this for TFS, I would be willing to check out other solutions. 

Thank you.

**Comment by jessehouwing** [comment]
There is a re-entry issue surrounding us giving you a save method, plus
there's all kinds of issues around the error handling that is a lot more
difficult. So we don't expose a save method.

There is a trick you can use, which is to call transition to state, as the
only way to expose state transitions to you is to save the work item.

In order to generate a tree you'll have to save the first level of the
tree, this will trigger the aggregator on these new work items. Then you
can trigger another set of rules that generate the 2nd level of work items.
That will trigger another rule that will generate the 3rd level of work
items.

You may need to keep a bit of state in a custom field or in the history to
track which work items have been generated and which haven't.

On 26 Apr 2018 17:50, "IronGem" <notifications@github.com> wrote:

Thank you for the excellent plugin. Our organization relies on this
extensively.

My current situation is most of our new projects follow a pattern so we
need a standard tree/set of Work items when a new project is approved. I
have been looking into the MakeNewWorkItem method which looks like it will
work for the most part. The only issue I have, is how to be able to link
all of the new work items in a tree when the tree will be 2-3 levels deep
(parent-child relationships)? The AddWorkItemLink method only works if at
least one of the items is already saved in TFS. Is there a .Save() method
in the IWorkItemExposed class that could be used to facilitate this?
Also, Is there any way to create custom classes or enums while using C#
code? This ability would make dynamically generating work items based on a
template much easier.

If this functionality is outside the scope of this tool, please let me
know. If anyone knows of a tool that already does this for TFS, I would be
willing to check out other solutions.

Thank you.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tfsaggregator/tfsaggregator/issues/287>, or mute the
thread

**Comment by giuliov** [comment]
Maybe it can be implemented with a cascade of rules.

The first rule triggers when you create the top-level object
```
  <rule name="CreateFeatureStandardUserStory" appliesTo="Feature" changes="New">
      <![CDATA[
    var parentFeature = self;
    var parentTitle = parentFeature.GetField<string>("System.Title", "TITLE IS MISSING");
    if (!parentFeature.HasChildren())
    {
      string targetProject = parentFeature.GetField<string>("System.TeamProject", "PROJECT IS MISSING");
      var standardTaskTitles = new string[] { "Standard User Story", "Another Standard User Story" };
      foreach (string title in standardTaskTitles) {
        var childTask = store.MakeNewWorkItem(targetProject, "User Story");
        childTask["System.Title"] = title;
        childTask["System.Description"] = "User Story auto-generated for " + parentTitle;
        childTask.AddWorkItemLink(parentFeature, WorkItemImplementationBase.ParentRelationship);
      }
    } else {
      logger.Log(LogLevel.Information, "Feature {1} #{0} has already children.", parentFeature.Id, parentTitle);
    }
]]></rule>
```

then another rule for the newly created children
```
  <rule name="CreateUserStoryStandardTasks" appliesTo="User Story" changes="New">
      <![CDATA[
    var parentUserStory = self;
    var parentTitle = parentUserStory.GetField<string>("System.Title", "TITLE IS MISSING");
    if (!parentUserStory.HasChildren())
    {
      string targetProject = parentUserStory.GetField<string>("System.TeamProject", "PROJECT IS MISSING");
      var standardTaskTitles = new string[] { "Design", "Implementation", "Documentation", "Code Review", "DBA Review", "Deploy to Test", "Test", "Prep for Demo", "Deploy to Prod", "Test in Prod", "Deploy to DR" };
      foreach (string title in standardTaskTitles) {
        var childTask = store.MakeNewWorkItem(targetProject, "Task");
        childTask["System.Title"] = title;
        childTask["System.Description"] = "Task auto-generated for " + parentTitle;
        childTask.AddWorkItemLink(parentUserStory, WorkItemImplementationBase.ParentRelationship);
      }
    } else {
      logger.Log(LogLevel.Information, "UserStory {1} #{0} has been tasked already.", parentUserStory.Id, parentTitle);
    }
]]></rule>
```

note in both rules the `changes="New"` clause that will trigger the rule only for new records.

I know that one level works, not sure about cascading: try and let us know.

**Comment by jessehouwing** [comment]
There is a re-entry issue surrounding us giving you a save method, plus
there's all kinds of issues around the error handling that is a lot more
difficult. So we don't expose a save method.

There is a trick you can use, which is to call transition to state, as the
only way to expose state transitions to you is to save the work item.

In order to generate a tree you'll have to save the first level of the
tree, this will trigger the aggregator on these new work items. Then you
can trigger another set of rules that generate the 2nd level of work items.
That will trigger another rule that will generate the 3rd level of work
items.

You may need to keep a bit of state in a custom field or in the history

On 26 Apr 2018 17:50, "IronGem" <notifications@github.com> wrote:

Thank you for the excellent plugin. Our organization relies on this
extensively.

My current situation is most of our new projects follow a pattern so we
need a standard tree/set of Work items when a new project is approved. I
have been looking into the MakeNewWorkItem method which looks like it will
work for the most part. The only issue I have, is how to be able to link
all of the new work items in a tree when the tree will be 2-3 levels deep
(parent-child relationships)? The AddWorkItemLink method only works if at
least one of the items is already saved in TFS. Is there a .Save() method
in the IWorkItemExposed class that could be used to facilitate this?
Also, Is there any way to create custom classes or enums while using C#
code? This ability would make dynamically generating work items based on a
template much easier.

If this functionality is outside the scope of this tool, please let me
know. If anyone knows of a tool that already does this for TFS, I would be
willing to check out other solutions.

Thank you.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tfsaggregator/tfsaggregator/issues/287>, or mute the
thread

**Comment by IronGem** [comment]
Thank you for the suggestions.  This is how I finally implemented this idea.  The key to this model is the `Custom.ProjectTemplate` field which I added to the 2 upper level work items (TopHierarchyWI and MiddleHierarchyWI).  This is a visible field on the TopHierarchyWI layout tied to a global list.  On the MiddleHierarchyWI it is just a hidden field (listed in Fields, but not on the layout).  This way, a user only has to open the TopHierarchyWI, choose an option in the Project Template list and save.  Aggregator then generates one or more branches based on the choice. `Custom.ProjectTemplate` is then blanked out so the rule does not run multiple times. 


[TestPolicy.txt](https://github.com/tfsaggregator/tfsaggregator/files/2040422/TestPolicy.txt)


This could probably be refactored to be more efficient, but in this form I can create new branches and/or packages easily without interfering with previous ones.  I would only have to create a function for the MiddleWI, add case logic to both rules and add the new branch/project name to the GlobalList.

Thank you once again for all of your help and this amazing tool.
