### ISSUE TITLE
Viewing the Aggregator's 'Queue'

### ISSUE THREAD

**Issue by IronGem** [tfsaggregator/tfsaggregator#317]
We have been using TFS Aggregator for a few years now and our policy file has grown quite large.  I know that the more rules you have the longer it takes to process a work item, but it always seems like Aggregator is lagging by several hours now.  
Is there a way to view the 'queue' for the tool?  I'm looking to see how many items are waiting to be processed and maybe get a feel for how long it will be before any particular item is updated.  We had a DNS issue a few weeks ago that stopped Aggregator from running for a week or so, and I am trying to find out if it is still trying to process all of the changes that piled up while it was down.

Any thoughts would be appreciated.  Thank you.

**Comment by jessehouwing** [comment]
There is no such thing as a queue in tfs aggregator. Everything is in
process.

On 24 Jan 2019 15:57, "IronGem" <notifications@github.com> wrote:

We have been using TFS Aggregator for a few years now and our policy file
has grown quite large. I know that the more rules you have the longer it
takes to process a work item, but it always seems like Aggregator is
lagging by several hours now.
Is there a way to view the 'queue' for the tool? I'm looking to see how
many items are waiting to be processed and maybe get a feel for how long it
will be before any particular item is updated. We had a DNS issue a few
weeks ago that stopped Aggregator from running for a week or so, and I am
trying to find out if it is still trying to process all of the changes that
piled up while it was down.

Any thoughts would be appreciated. Thank you.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tfsaggregator/tfsaggregator/issues/317>, or mute the
thread

**Comment by IronGem** [comment]
Does that mean that on each Save in TFS, the Aggregator plugin immediately kicks off and processes the rules for that Work Item (multi-threaded) or does it have to wait until the previous work item has been processed?

**Comment by jessehouwing** [comment]
It runs in-process with TFS and is kicked off immediately after save. It
then runs async to complete on a worker thread in the TFS web service tier.
There may be an IIS request queue somewhere in there, but that's totally
out of our control.

**Comment by jessehouwing** [comment]
In case of an outage of TFS aggregator, there is nothing in place that will
process any missed events. You can use the TFS Aggregator commandline to
manually process all work items changed in a certain time period. Or use a
"batch change" from the TFS web ui to force a change to all impacted work
items.

**Comment by IronGem** [comment]
Ok, that answers the question then.  The worker thread can get backed up, but there is no way for us to see how many requests are waiting for processing.  That explains why it can take a few minutes or so before we see updates appear on work items.  Thank you for giving me a short overview on the way Aggregator processes changes.

**Comment by jessehouwing** [comment]
You may be able to use the tfs performance counters to get an idea of the number of in-progress tasks.
