### ISSUE TITLE
TFS 2015 Update 3 and TFS Aggregator 2.1 Alpha Generating Duplicate Child Tasks

### ISSUE THREAD

**Issue by jforst2** [tfsaggregator/tfsaggregator#325]
We have a Field, "Dependencies", which is a multi-value control that contains 28 Child Types a User can select in our Product Backlog Item WIT.  Once a user selects the Dependencies they want and Click Save, TFS executes our TFS Aggregator Polices file, which has a rule to read the Dependencies Field and then generate child Tasks for each dependency selected.  This rule uses, MakeNewWorkItem to create the Task, then sets various values, then creates a Link in the Child back to the Parent and then TransitionsToState "To Do".

Cases: 
1) If we open our PBI, select the dependencies we want and click to Save the PBI without changing anything else in the WIT, TFS Aggregator executes the Rule to generate Tasks and functions correctly, generating one Task for each dependency selected. SUCCESS

2) If we open our PBI and select the dependencies we want, then modify another field in the PBI at the same time and then click to Save the PBI, TFS Aggregator executes the Rule to generate Tasks and generates NOT One, but Two Tasks for each dependency selected. FAILURE...

3) Here we have a PBI with a parent Portfolio Epic which has a tab of fields that we sync from the Portfolio Epic to the PBI using a TFS Aggregator Rule.  So, in this case, if we Modify the Portfolio Epic field in the tab that will be synced, then open the PBI and select the dependencies we want, not modifying anything else in the PBI and then click to Save the PBI , The TFS Aggregator Policy file is executed and the first rule run is the SYNC of the Portfolio Epic to the PBI, then the Rule to generate Tasks is executed.  Again in this case, TFS Aggregator generates NOT One, but Two Tasks for each dependency selected.

What we discovered by using logging, is that in Case One, TFS Aggregator executes the Policy file only once.  In Case 2 and 3, TFS Aggregator executes the Policy File at minimum twice for each dependency selected due, we believe, to the Additional Changes that are made in the PBI.  In addition, The first time it is run, it creates the Tasks and Links, but it does not save them to the TFS Database, so when it runs the Second Time, the rule cannot detect that they are already created and generates a duplicate set of Tasks.

Question: 
Is there a way to force TFS to save the Tasks created during the First Run to the TFS Database, prior to TFS executing the TFS Aggregator Policy Rules a second time???

I have spent months updating our processes in TFS and this is now holding up our deployment to Production as we cannot be generating duplicate tasks....

Any help will be greatly appreciated...

**Comment by jessehouwing** [comment]
Can you share the rule? Privately if needed?

Do you have debug logs you can share?

Which fields are being changed when this goes wrong?

**Comment by giuliov** [comment]
I suggest to use this approach: never assume what is the state of the system but get it on-the-fly. In your case, use the same rule for both _work item created_ and _updated_ events; use a FluentQuery or loop in the Children collection to get the list of linked Tasks; finally loop the values in the _Dependencies_ Field. If you find a matching Task, you have nothing to do, otherwise create and link the missing Tasks.
For this to work, you must have a unambiguous test to check if a Tasks was created by the Rule or not; maybe you can use the Title or a custom Field.

**Comment by jforst2** [comment]
Jesse, 

Find attached in zip file, a cut down test version of our PBI, GlobalList.lst and Policy file for the Child Task Generation.   Please note that the Dependencies field is using a Multi-Value Control Extension (non-Microsoft) which may prevent you from using it.

As far as the fields being changed:

1) Dependencies - This is field to configure dependencies requested and is used by the TFS Aggregator Rule to generate tasks.

2) In Addition to changing the Dependencies field, also change at least one of the below to force the duplicate task creation.
   Team
   Type
   Version Planned

Let me work on the log file and see if I can get it scrubbed so I can send it to you.



[TFS Aggregator Auto-Task Issue.zip](https://github.com/tfsaggregator/tfsaggregator/files/3307571/TFS.Aggregator.Auto-Task.Issue.zip)

**Comment by giuliov** [comment]
You can send an email to tfsaggregator at outlook.com if you want a private channel.

**Comment by jforst2** [comment]
Jesse,

Since I only have the full policies file in place to test with, I have tested in the following manner and added the log file attached.

Case 3:
   1) Created and opened new WIT, Product Backlog Item" linked to Parent "Portfolio Epic".
   2) Changed Dependencies Field to create 2 Child Tasks:
           a) [Architecture (Arch)]  (Will create a task with title "Arch Auto-Task"
           b) [Client Service Management (CSM/CSX)] (Will create a task with title "CSM/CSX Auto-Task"
    3) Saved PBI
    4) Refreshed WIT in Visual Studio or Web and look at links and see 2 tasks generated for each Dependency.

Please review attached log file to see how the aggregator is running multiple times for this single save and creates duplicate tasks...

[TFSAggregator_PlugInLog.zip](https://github.com/tfsaggregator/tfsaggregator/files/3308021/TFSAggregator_PlugInLog.zip)

**Comment by jforst2** [comment]
Sorry, hit wrong button closing  so I reopened issue

**Comment by jforst2** [comment]
giuliov,

I do test for all existing tasks in the TFS Aggregator rule, however, it appears during the execution of the policy file, After the first run when it creates the first set of new Tasks, they are not committed to the database until after TFS releases TFS Aggregator.  Since the policy file is being run multiple times due to multiple changes occurring, the second time the policy file is executed by TFS/TFS Aggregator, and I again test for all existing Tasks, they are still not found, as they have not been created in the Database yet.  Due to this it creates duplicate copies of the Tasks.

**Comment by jforst2** [comment]
Sorry, hit wrong button closing so I reopened issue

**Comment by jforst2** [comment]
Please any help you can provide will be greatly appreciated...

**Comment by jessehouwing** [comment]
There isn't much you can do about this. Due to the async nature and the tasks not having been committed yet during the run, multiple changes can cause these issues.

Right now no immediate solution springs to mind due to the way wit data is cached in the aggregator until save.

This is also to prevent even more changes from being processed in parrallel.

**Comment by jforst2** [comment]
Thanks Jesse, this is what I was worried about.
So, there is no way for the Aggregator to see its own cache to see if there are pending saves of Tasks?

**Comment by jessehouwing** [comment]
Even if it could, with multiple Application Tiers there is no way to
communicate between processes.

Im still thinking of a strategy that might work. Not sure if we ever got so
far as to expose the changed field value. That way you only trigger when
the field has changed. You can also look at previous revisions to see which
tasks should already have been created. Then run a timer based job (windows
task scheduler + aggregator commandline) to resolve any issues due to
conflicts that prevented the children from being created.

Another option is to add a hidden field, use the rule that detects the
changed multiselect, sets the hidden field and saves. That should trigger a
new revision that an trigger just the rule to update children.

**Comment by jforst2** [comment]
Ok, yes application tiers would definitely cause an issue with reading the cache.

I like the idea of the Hidden Field.  I will do a little testing with this and see  what happens. I will let you know.

Thanks again for your help.

**Comment by ghost** [comment]
Sorry this took so long to get back on this.  I used a modified example of the hidden field and resolved my issue.  Thanks.
