### ISSUE TITLE
 Can I select a work item that has the desired value by scanning and filtering all work items

### ISSUE THREAD

**Issue by DoganTahir** [tfsaggregator/tfsaggregator#335]
I want to search the whole user story. I just want to select work items that have the value I want through a field.

**Comment by giuliov** [comment]
Not from a rule because it makes little sense.

If your scenario is to pass existing work items and make sure they conform to a set of rules, you can use the ConsoleApp to apply a set of rules to all work items returned from a WIQL query.

```
TFSAggregator2.ConsoleApp.exe run --policyFile=myrules.policies --teamProjectCollectionUrl=http://localhost:8080/tfs/DefaultCollection --teamProjectName=TfsAggregatorTest1 --logLevel=diagnostic --query "SELECT System.ID, System.Title FROM WorkItems WHERE [System.TeamProject] = 'TfsAggregatorTest1' AND [System.WorkItemType] = 'User Story' "
```

See [WIQL Syntax](https://docs.microsoft.com/en-us/azure/devops/boards/queries/wiql-syntax). 
**Note**: you cannot use query macros here.

Maybe you can explain your scenario better.
