### ISSUE TITLE
Iteration id and path on some date

### ISSUE THREAD

**Issue by gubin-i** [tfsaggregator/tfsaggregator#349]
Hello!

I am trying to solve a problem where, by adding a link from Task to Bug, I need to initialize the Task's fields in a rule:
self ["System.IterationId"] = id; // id of the current iteration
self ["System.IterationPath"] = path; // path of the current iteration

I've tried several implementations of the function to get the current iteration, but they all fail compiler checks - swearing for invalid namespaces.

Is it possible to extend the types and namespaces used, in particular, add Microsoft.TeamFoundation.Work.WebApi.dll, Microsoft.TeamFoundation.Core.WebApi.dll, System.Uri or add a method to self to get iterated over uri in the collection, team project name and date.

If this problem has already been solved otherwise, I ask you to suggest some tips on how to do this.

thanks in advance

**Comment by jessehouwing** [comment]
No, currently not possible. We have a wrapper around the standard object model and we limit the number of namespaces we depend on in order to support all the different versions of TFS we support. There have been many changes where types have moved from one assembly to another.

If you need more, you can either use their fully qualified name for some object types that are loaded into the process. Or you'll need to use reflection and/or dynamic to pull in more than we (want to) support.
