### ISSUE TITLE
Timeline for 2.6

### ISSUE THREAD

**Issue by millusdk** [tfsaggregator/tfsaggregator#355]
Hello,

First of all thank you for making this product, it helps us out a lot at our project.

We are looking at upgrading our Azure Devops Server from 2019 to 2020, as part of this we need to update TFS Aggregator, and I was wondering if you had a timeline for when you expect a final version of 2.6 to be released.

Best regards,
Emil

**Comment by jessehouwing** [comment]
There won't be a final version more final than the versions we release now.
We no longer have client environments that use the TFS Aggregator server
plugin. We're trying to move everything to the aggregator-cli which relies
on Azure functions/Docker.

To reflect that we do not do extensive final verification testing on the
plugin variant, all versions have the Beta label on them.

But there haven't been any real changes to the product in a long time and
Azure Devops hasn't broken its contracts either. The reason you need a new
a new version is because the version numbers on the server and client
object model had changed.

If you need a long term solution, move to aggregator-cli, in the short
term, 2.6 is as much final as 2.5 at the moment.

**Comment by millusdk** [comment]
Thank you very much for your fast response! It makes sense that you are unable to provide a final version if you don't have an environment that uses the server plugin.

Is the new CLI version only supported on Azure functions and Docker, or is there a way to run it as a windows service or something similar? I am not sure we are able to run Docker in our hosting environment, and Azure functions are not a possibility either.

**Comment by jessehouwing** [comment]
The docker images can run on windows. The Azure Functions Runtime too if
I'm not mistaking, though I don't think that is a configuration we
currently test.

There is no windows service or IIS website you can deploy. This solution
allows us to use the same technology for Azure Devops as well as
on-premise.

We used do have a server plugin and an IIS webservice version and keeping
everything working and supporting across all these different versions is a
maintenance headache. Hence our aim to move towards a single solution that
works everywhere.

**Comment by millusdk** [comment]
Again thank you for your quick response.
It makes a lot of sense to want to simplify how things are running, maintaining multiple versions is a headache as you write, especially for a small open source project as this.
I will look into figuring out if we can run either docker or the Azure functions version locally.

Thank you very much for answering my questions, I will close this issue.
